/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandRouteImport } from './routes/command'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DiligenceRouteImport } from './routes/diligence'
import { Route as EstateRouteImport } from './routes/estate'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as FrontierRouteImport } from './routes/frontier'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HubRouteImport } from './routes/hub'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as KillinchuRouteImport } from './routes/killinchu'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as OrgansRouteImport } from './routes/organs'
import { Route as ProvenanceRouteImport } from './routes/provenance'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as TrajectoryRouteImport } from './routes/trajectory'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DiligenceRoute = DiligenceRouteImport.update({
  id: '/diligence',
  path: '/diligence',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateRoute = EstateRouteImport.update({
  id: '/estate',
  path: '/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontierRoute = FrontierRouteImport.update({
  id: '/frontier',
  path: '/frontier',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const KillinchuRoute = KillinchuRouteImport.update({
  id: '/killinchu',
  path: '/killinchu',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgansRoute = OrgansRouteImport.update({
  id: '/organs',
  path: '/organs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvenanceRoute = ProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajectoryRoute = TrajectoryRouteImport.update({
  id: '/trajectory',
  path: '/trajectory',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/contribute': typeof ContributeRoute
  '/diligence': typeof DiligenceRoute
  '/estate': typeof EstateRoute
  '/formulas': typeof FormulasRoute
  '/frontier': typeof FrontierRoute
  '/graph': typeof GraphRoute
  '/hub': typeof HubRoute
  '/identity': typeof IdentityRoute
  '/killinchu': typeof KillinchuRoute
  '/ledger': typeof LedgerRoute
  '/lifecycle': typeof LifecycleRoute
  '/organs': typeof OrgansRoute
  '/provenance': typeof ProvenanceRoute
  '/publish': typeof PublishRoute
  '/registry': typeof RegistryRoute
  '/trajectory': typeof TrajectoryRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/contribute': typeof ContributeRoute
  '/diligence': typeof DiligenceRoute
  '/estate': typeof EstateRoute
  '/formulas': typeof FormulasRoute
  '/frontier': typeof FrontierRoute
  '/graph': typeof GraphRoute
  '/hub': typeof HubRoute
  '/identity': typeof IdentityRoute
  '/killinchu': typeof KillinchuRoute
  '/ledger': typeof LedgerRoute
  '/lifecycle': typeof LifecycleRoute
  '/organs': typeof OrgansRoute
  '/provenance': typeof ProvenanceRoute
  '/publish': typeof PublishRoute
  '/registry': typeof RegistryRoute
  '/trajectory': typeof TrajectoryRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command': typeof CommandRoute
  '/contribute': typeof ContributeRoute
  '/diligence': typeof DiligenceRoute
  '/estate': typeof EstateRoute
  '/formulas': typeof FormulasRoute
  '/frontier': typeof FrontierRoute
  '/graph': typeof GraphRoute
  '/hub': typeof HubRoute
  '/identity': typeof IdentityRoute
  '/killinchu': typeof KillinchuRoute
  '/ledger': typeof LedgerRoute
  '/lifecycle': typeof LifecycleRoute
  '/organs': typeof OrgansRoute
  '/provenance': typeof ProvenanceRoute
  '/publish': typeof PublishRoute
  '/registry': typeof RegistryRoute
  '/trajectory': typeof TrajectoryRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command'
    | '/contribute'
    | '/diligence'
    | '/estate'
    | '/formulas'
    | '/frontier'
    | '/graph'
    | '/hub'
    | '/identity'
    | '/killinchu'
    | '/ledger'
    | '/lifecycle'
    | '/organs'
    | '/provenance'
    | '/publish'
    | '/registry'
    | '/trajectory'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command'
    | '/contribute'
    | '/diligence'
    | '/estate'
    | '/formulas'
    | '/frontier'
    | '/graph'
    | '/hub'
    | '/identity'
    | '/killinchu'
    | '/ledger'
    | '/lifecycle'
    | '/organs'
    | '/provenance'
    | '/publish'
    | '/registry'
    | '/trajectory'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/command'
    | '/contribute'
    | '/diligence'
    | '/estate'
    | '/formulas'
    | '/frontier'
    | '/graph'
    | '/hub'
    | '/identity'
    | '/killinchu'
    | '/ledger'
    | '/lifecycle'
    | '/organs'
    | '/provenance'
    | '/publish'
    | '/registry'
    | '/trajectory'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandRoute: typeof CommandRoute
  ContributeRoute: typeof ContributeRoute
  DiligenceRoute: typeof DiligenceRoute
  EstateRoute: typeof EstateRoute
  FormulasRoute: typeof FormulasRoute
  FrontierRoute: typeof FrontierRoute
  GraphRoute: typeof GraphRoute
  HubRoute: typeof HubRoute
  IdentityRoute: typeof IdentityRoute
  KillinchuRoute: typeof KillinchuRoute
  LedgerRoute: typeof LedgerRoute
  LifecycleRoute: typeof LifecycleRoute
  OrgansRoute: typeof OrgansRoute
  ProvenanceRoute: typeof ProvenanceRoute
  PublishRoute: typeof PublishRoute
  RegistryRoute: typeof RegistryRoute
  TrajectoryRoute: typeof TrajectoryRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diligence': {
      id: '/diligence'
      path: '/diligence'
      fullPath: '/diligence'
      preLoaderRoute: typeof DiligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate': {
      id: '/estate'
      path: '/estate'
      fullPath: '/estate'
      preLoaderRoute: typeof EstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontier': {
      id: '/frontier'
      path: '/frontier'
      fullPath: '/frontier'
      preLoaderRoute: typeof FrontierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/killinchu': {
      id: '/killinchu'
      path: '/killinchu'
      fullPath: '/killinchu'
      preLoaderRoute: typeof KillinchuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organs': {
      id: '/organs'
      path: '/organs'
      fullPath: '/organs'
      preLoaderRoute: typeof OrgansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provenance': {
      id: '/provenance'
      path: '/provenance'
      fullPath: '/provenance'
      preLoaderRoute: typeof ProvenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajectory': {
      id: '/trajectory'
      path: '/trajectory'
      fullPath: '/trajectory'
      preLoaderRoute: typeof TrajectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandRoute: CommandRoute,
  ContributeRoute: ContributeRoute,
  DiligenceRoute: DiligenceRoute,
  EstateRoute: EstateRoute,
  FormulasRoute: FormulasRoute,
  FrontierRoute: FrontierRoute,
  GraphRoute: GraphRoute,
  HubRoute: HubRoute,
  IdentityRoute: IdentityRoute,
  KillinchuRoute: KillinchuRoute,
  LedgerRoute: LedgerRoute,
  LifecycleRoute: LifecycleRoute,
  OrgansRoute: OrgansRoute,
  ProvenanceRoute: ProvenanceRoute,
  PublishRoute: PublishRoute,
  RegistryRoute: RegistryRoute,
  TrajectoryRoute: TrajectoryRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
